### ISSUE TITLE
Concurrent Modification Exception in display code

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1159]
2021-03-21T22:07:32.333492 tid3176 [IFO,dev:Camera-1] Device adapter requests invalid values ( 0, 0) for property: CircularBufferFrameCount
2021-03-21T22:07:32.858948 tid10900 [IFO,App] Thread 19 (AWT-EventQueue-0) terminated with uncaught exception
2021-03-21T22:07:32.858948 tid10900 [IFO,App] java.util.ConcurrentModificationException
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at java.util.ArrayList.<init>(ArrayList.java:178)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at org.micromanager.data.internal.StorageSinglePlaneTiffSeries.getAnyImage(StorageSinglePlaneTiffSeries.java:287)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at org.micromanager.data.internal.DefaultDatastore.getAnyImage(DefaultDatastore.java:177)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at org.micromanager.display.internal.displaywindow.imagej.ImageJBridge.makeBlankImage(ImageJBridge.java:577)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at org.micromanager.display.internal.displaywindow.imagej.ImageJBridge.getMMImage(ImageJBridge.java:568)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at org.micromanager.display.internal.displaywindow.imagej.MMVirtualStack.getProcessor(MMVirtualStack.java:130)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at ij.CompositeImage.updateImage(CompositeImage.java:259)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at ij.gui.ImageCanvas.paint(ImageCanvas.java:222)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at org.micromanager.display.internal.displaywindow.imagej.MMImageCanvas.paint(MMImageCanvas.java:89)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at ij.gui.ImageCanvas.update(ImageCanvas.java:203)
2021-03-21T22:07:32.858948 tid10900 [IFO,App]   at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)

and:

2021-03-21T22:05:48.242344 tid3176 [IFO,dev:Camera-1] Device adapter requests invalid values ( 0, 0) for property: CircularBufferFrameCount
2021-03-21T22:05:49.177375 tid10900 [IFO,App] Thread 19 (AWT-EventQueue-0) terminated with uncaught exception
2021-03-21T22:05:49.177375 tid10900 [IFO,App] java.util.ConcurrentModificationException
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at java.util.ArrayList.<init>(ArrayList.java:178)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at org.micromanager.data.internal.StorageSinglePlaneTiffSeries.getAnyImage(StorageSinglePlaneTiffSeries.java:287)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at org.micromanager.data.internal.DefaultDatastore.getAnyImage(DefaultDatastore.java:177)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at org.micromanager.display.inspector.internal.panels.intensity.ChannelIntensityController.statsOrRangeChanged(ChannelIntensityController.java:418)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at org.micromanager.display.inspector.internal.panels.intensity.ChannelIntensityController.setStats(ChannelIntensityController.java:489)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at org.micromanager.display.inspector.internal.panels.intensity.IntensityInspectorPanelController$1.run(IntensityInspectorPanelController.java:423)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at org.micromanager.internal.utils.CoalescentEDTRunnablePool$2.run(CoalescentEDTRunnablePool.java:132)
2021-03-21T22:05:49.177375 tid10900 [IFO,App]   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)

**Comment by nicost** [comment]
Presumably fixed in #1169
