### ISSUE TITLE
mm2: When loading a file larger than JVM memory size, file loading aborts silently

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#121]
JVM started with -XMx2000m.  Loading a 2.6 GB file results in the following stack trace (without any output for the user):

2015-12-11T13:31:14.339347 tid0x1271cd000 [IFO,App] Thread 17 (AWT-EventQueue-0) terminated with uncaught exception
2015-12-11T13:31:14.339382 tid0x1271cd000 [IFO,App] java.lang.OutOfMemoryError: Direct buffer memory
2015-12-11T13:31:14.339610 tid0x1271cd000 [IFO,App]   at java.nio.Bits.reserveMemory(Bits.java:658)
2015-12-11T13:31:14.339621 tid0x1271cd000 [IFO,App]   at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
2015-12-11T13:31:14.339626 tid0x1271cd000 [IFO,App]   at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
2015-12-11T13:31:14.339630 tid0x1271cd000 [IFO,App]   at org.micromanager.internal.utils.DirectBuffers.bufferFromShorts(DirectBuffers.java:24)
2015-12-11T13:31:14.339634 tid0x1271cd000 [IFO,App]   at org.micromanager.internal.utils.DirectBuffers.bufferFromArray(DirectBuffers.java:75)
2015-12-11T13:31:14.339637 tid0x1271cd000 [IFO,App]   at org.micromanager.data.internal.DefaultImage.<init>(DefaultImage.java:142)
2015-12-11T13:31:14.339642 tid0x1271cd000 [IFO,App]   at org.micromanager.data.internal.multipagetiff.MultipageTiffReader.readImage(MultipageTiffReader.java:284)
2015-12-11T13:31:14.339646 tid0x1271cd000 [IFO,App]   at org.micromanager.data.internal.multipagetiff.StorageMultipageTiff.getImage(StorageMultipageTiff.java:685)
2015-12-11T13:31:14.339650 tid0x1271cd000 [IFO,App]   at org.micromanager.data.internal.DefaultDatastore.getImage(DefaultDatastore.java:131)
2015-12-11T13:31:14.339654 tid0x1271cd000 [IFO,App]   at org.micromanager.data.internal.DefaultDatastore.copyFrom(DefaultDatastore.java:90)
2015-12-11T13:31:14.339657 tid0x1271cd000 [IFO,App]   at org.micromanager.data.internal.DefaultDataManager.loadData(DefaultDataManager.java:169)
2015-12-11T13:31:14.339661 tid0x1271cd000 [IFO,App]   at org.micromanager.data.internal.DefaultDataManager.promptForDataToLoad(DefaultDataManager.java:143)
2015-12-11T13:31:14.339670 tid0x1271cd000 [IFO,App]   at org.micromanager.internal.menus.FileMenu.promptToOpenFile(FileMenu.java:106)
2015-12-11T13:31:14.339674 tid0x1271cd000 [IFO,App]   at org.micromanager.internal.menus.FileMenu.access$100(FileMenu.java:29)
2015-12-11T13:31:14.339678 tid0x1271cd000 [IFO,App]   at org.micromanager.internal.menus.FileMenu$3.run(FileMenu.java:77)
2015-12-11T13:31:14.339681 tid0x1271cd000 [IFO,App]   at org.micromanager.internal.utils.GUIUtils$2.actionPerformed(GUIUtils.java:353)
2015-12-11T13:31:14.339685 tid0x1271cd000 [IFO,App]   at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
2015-12-11T13:31:14.339689 tid0x1271cd000 [IFO,App]   at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
2015-12-11T13:31:14.339693 tid0x1271cd000 [IFO,App]   at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
2015-12-11T13:31:14.339697 tid0x1271cd000 [IFO,App]   at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
2015-12-11T13:31:14.339700 tid0x1271cd000 [IFO,App]   at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
2015-12-11T13:31:14.339704 tid0x1271cd000 [IFO,App]   at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
2015-12-11T13:31:14.339708 tid0x1271cd000 [IFO,App]   at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
2015-12-11T13:31:14.339711 tid0x1271cd000 [IFO,App]   at java.awt.MenuItem.processEvent(MenuItem.java:628)
2015-12-11T13:31:14.339715 tid0x1271cd000 [IFO,App]   at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
2015-12-11T13:31:14.339718 tid0x1271cd000 [IFO,App]   at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
2015-12-11T13:31:14.339723 tid0x1271cd000 [IFO,App]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
2015-12-11T13:31:14.339727 tid0x1271cd000 [IFO,App]   at java.awt.EventQueue.access$500(EventQueue.java:97)
2015-12-11T13:31:14.339731 tid0x1271cd000 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:709)
2015-12-11T13:31:14.339734 tid0x1271cd000 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:703)
2015-12-11T13:31:14.339740 tid0x1271cd000 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2015-12-11T13:31:14.339744 tid0x1271cd000 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
2015-12-11T13:31:14.339748 tid0x1271cd000 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
2015-12-11T13:31:14.339751 tid0x1271cd000 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:731)
2015-12-11T13:31:14.339755 tid0x1271cd000 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:729)
2015-12-11T13:31:14.339758 tid0x1271cd000 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2015-12-11T13:31:14.339762 tid0x1271cd000 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
2015-12-11T13:31:14.339765 tid0x1271cd000 [IFO,App]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
2015-12-11T13:31:14.339770 tid0x1271cd000 [IFO,App]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
2015-12-11T13:31:14.339773 tid0x1271cd000 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
2015-12-11T13:31:14.339777 tid0x1271cd000 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
2015-12-11T13:31:14.339781 tid0x1271cd000 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2015-12-11T13:31:14.339784 tid0x1271cd000 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
2015-12-11T13:31:14.339788 tid0x1271cd000 [IFO,App]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ChrisWeisiger** [comment]
The key for reproducing this appears to be the MaxDirectMemorySize parameter, not the -Xmx parameter. When I modify the mmimagej launch script to use "-XX:MaxDirectMemorySize=1G" instead of the default 1000G, then I'm able to reproduce this when loading a 2.4GB dataset. 

I've committed a change that will show an error dialog if we run out of memory while loading image data into RAM.
