### ISSUE TITLE
Null Pointer Exception in DataViewerDidBecomeActive Event

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1214]
2021-04-28T15:53:07.397177 tid10876 [IFO,App] Exception thrown by EventBus subscriber:
                                    [       ] Event: org.micromanager.display.internal.event.DataViewerDidBecomeActiveEvent@42862c94
                                    [       ] EventBus: com.google.common.eventbus.EventBus@4c5736cf
                                    [       ] Subscriber: org.micromanager.display.inspector.internal.InspectorController@1341860
                                    [       ] Subscriber Method: public void org.micromanager.display.inspector.internal.InspectorController.onEvent(org.micromanager.display.internal.event.DataViewerDidBecomeActiveEvent)
                                    [       ] java.lang.NullPointerException in Thread[AWT-EventQueue-0,6,main]
                                    [       ]   at org.micromanager.display.internal.displaywindow.DisplayController.getDisplayedImages(DisplayController.java:929)
                                    [       ]   at org.micromanager.display.inspector.internal.panels.metadata.PlaneMetadataInspectorPanelController.attachDataViewer(PlaneMetadataInspectorPanelController.java:172)
                                    [       ]   at org.micromanager.display.inspector.internal.InspectorController.attachToDataViewer(InspectorController.java:442)
                                    [       ]   at org.micromanager.display.inspector.internal.InspectorController.access$500(InspectorController.java:68)
                                    [       ]   at org.micromanager.display.inspector.internal.InspectorController$FrontmostAttachmentStrategy.viewerActivated(InspectorController.java:585)
                                    [       ]   at org.micromanager.display.inspector.internal.InspectorController.onEvent(InspectorController.java:417)
                                    [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                    [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                    [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                    [       ]   at java.lang.reflect.Method.invoke(Method.java:498)
                                    [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                                    [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                    [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                    [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                    [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                    [       ]   at org.micromanager.display.internal.DataViewerCollection.onEvent(DataViewerCollection.java:135)
                                    [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                    [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                    [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                    [       ]   at java.lang.reflect.Method.invoke(Method.java:498)
                                    [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                                    [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                    [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                    [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                    [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                    [       ]   at org.micromanager.display.AbstractDataViewer.postEvent(AbstractDataViewer.java:101)
                                    [       ]   at org.micromanager.display.internal.displaywindow.DisplayController.frameDidBecomeActive(DisplayController.java:304)
                                    [       ]   at org.micromanager.display.internal.displaywindow.DisplayUIController.windowActivated(DisplayUIController.java:1918)
                                    [       ]   at java.awt.Window.processWindowEvent(Window.java:2066)
                                    [       ]   at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
                                    [       ]   at java.awt.Window.processEvent(Window.java:2013)
                                    [       ]   at java.awt.Component.dispatchEventImpl(Component.java:4889)
                                    [       ]   at java.awt.Container.dispatchEventImpl(Container.java:2295)
                                    [       ]   at java.awt.Window.dispatchEventImpl(Window.java:2746)
                                    [       ]   at java.awt.Component.dispatchEvent(Component.java:4711)
                                    [       ]   at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
                                    [       ]   at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:995)
                                    [       ]   at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:488)
                                    [       ]   at java.awt.Component.dispatchEventImpl(Component.java:4760)
                                    [       ]   at java.awt.Container.dispatchEventImpl(Container.java:2295)
                                    [       ]   at java.awt.Window.dispatchEventImpl(Window.java:2746)
                                    [       ]   at java.awt.Component.dispatchEvent(Component.java:4711)
                                    [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
                                    [       ]   at java.awt.EventQueue.access$500(EventQueue.java:97)
                                    [       ]   at java.awt.EventQueue$3.run(EventQueue.java:709)
                                    [       ]   at java.awt.EventQueue$3.run(EventQueue.java:703)
                                    [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
                                    [       ]   at java.awt.EventQueue$4.run(EventQueue.java:731)
                                    [       ]   at java.awt.EventQueue$4.run(EventQueue.java:729)
                                    [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                                    [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
                                    [       ]   at java.awt.SentEvent.dispatch(SentEvent.java:70)
                                    [       ]   at java.awt.DefaultKeyboardFocusManager$DefaultKeyboardFocusManagerSentEvent.dispatch(DefaultKeyboardFocusManager.java:217)
                                    [       ]   at java.awt.DefaultKeyboardFocusManager.sendMessage(DefaultKeyboardFocusManager.java:244)
                                    [       ]   at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:366)
                                    [       ]   at java.awt.Component.dispatchEventImpl(Component.java:4760)
                                    [       ]   at java.awt.Container.dispatchEventImpl(Container.java:2295)
                                    [       ]   at java.awt.Window.dispatchEventImpl(Window.java:2746)
                                    [       ]   at java.awt.Component.dispatchEvent(Component.java:4711)
                                    [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
                                    [       ]   at java.awt.EventQueue.access$500(EventQueue.java:97)
                                    [       ]   at java.awt.EventQueue$3.run(EventQueue.java:709)
                                    [       ]   at java.awt.EventQueue$3.run(EventQueue.java:703)
                                    [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
                                    [       ]   at java.awt.EventQueue$4.run(EventQueue.java:731)
                                    [       ]   at java.awt.EventQueue$4.run(EventQueue.java:729)
                                    [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                                    [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
                                    [       ]   at java.awt.SequencedEvent.dispatch(SequencedEvent.java:128)
                                    [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
                                    [       ]   at java.awt.EventQueue.access$500(EventQueue.java:97)
                                    [       ]   at java.awt.EventQueue$3.run(EventQueue.java:709)
                                    [       ]   at java.awt.EventQueue$3.run(EventQueue.java:703)
                                    [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
                                    [       ]   at java.awt.EventQueue$4.run(EventQueue.java:731)
                                    [       ]   at java.awt.EventQueue$4.run(EventQueue.java:729)
                                    [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                                    [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
                                    [       ]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                                    [       ]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                                    [       ]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                                    [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                                    [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                                    [       ]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nicost** [comment]
Fixed in #1215
