### ISSUE TITLE
Multi monitor setup prevents start on Linux

### ISSUE THREAD

**Issue by ianhi** [micro-manager/micro-manager#1427]
When I have just my laptop screen micromanager launches without issue. However, if I plug in an external monitor then launch fails with this error:

```
2022-03-18T12:13:14.514086 tid140471726065216 [IFO,LogManager] Enabled logging to stderr
2022-03-18T12:13:14.534474 tid140471726065216 [IFO,LogManager] Enabled primary log file /tmp/CoreLog20220318T121314_pid367771.txt
2022-03-18T12:13:14.534588 tid140471726065216 [IFO,App] User: ian
2022-03-18T12:13:14.534601 tid140471726065216 [IFO,App] Host: fermented-beans
2022-03-18T12:13:14.534615 tid140471726065216 [IFO,App] MM Studio version: 2.0.x dev
2022-03-18T12:13:14.534632 tid140471726065216 [IFO,App] MMCore version 10.2.0
2022-03-18T12:13:14.534642 tid140471726065216 [IFO,App] Device API version 70, Module API version 10
2022-03-18T12:13:14.534649 tid140471726065216 [IFO,App] Operating System: Linux (amd64) 5.15.23-76051523-generic
2022-03-18T12:13:14.534656 tid140471726065216 [IFO,App] JVM: OpenJDK 64-Bit Server VM, version 17.0.2, 64-bit
2022-03-18T12:13:14.536561 tid140471726065216 [IFO,App] Finished waiting for plugins to load
2022-03-18T12:13:14.762240 tid140471726065216 [IFO,App] Thread 1 (main) terminated with uncaught exception
2022-03-18T12:13:14.762510 tid140471726065216 [IFO,App] java.lang.NullPointerException: Cannot invoke "java.awt.GraphicsConfiguration.getBounds()" because "config" is null
2022-03-18T12:13:14.762558 tid140471726065216 [IFO,App]   at org.micromanager.internal.dialogs.IntroDlg.<init>(IntroDlg.java:216)
2022-03-18T12:13:14.762566 tid140471726065216 [IFO,App]   at org.micromanager.internal.MMStudio.<init>(MMStudio.java:370)
2022-03-18T12:13:14.762570 tid140471726065216 [IFO,App]   at org.micromanager.internal.MMStudio.main(MMStudio.java:195)
```

which is coming from this code: 
https://github.com/micro-manager/micro-manager/blob/47298d8df3a3c8013a900e5d7274a8c7e46948a7/mmstudio/src/main/java/org/micromanager/internal/dialogs/IntroDlg.java#L215-L216

Interestingly if I start it with just my laptop open, then plug in an external monitor it seems to work fine.

**Comment by ianhi** [comment]
I Suspect part of the core of the issue is somewhere here:

https://github.com/micro-manager/micro-manager/blob/47298d8df3a3c8013a900e5d7274a8c7e46948a7/mmstudio/src/main/java/org/micromanager/internal/utils/GUIUtils.java#L214-L243

**Comment by nicost** [comment]
Please try again with JDK 8.  I ran a similar setup yesterday on Windows and had no issues plugging an external monitor in, so if the problem persists, exact steps to reproduce the problem will be essential.  Or, if you are setup to debug Java code, put some break points in the relevant code and see what is going on.

**Comment by ianhi** [comment]
annoyingly difficult to get jdk-8 to be used it seems. even after `sudo apt install openjdk-8-jre openjdk-8-jdk` and `sudo apt remove openjdk-17-jdk openjdk-17-jre` it was still defaulting to version 17 :/ took some conda trickery.

Do I also need to recompile with jdk8?

**Comment by ianhi** [comment]
recompiled with jdk8. Still failing with multiple monitors

**Comment by ianhi** [comment]
(pymm) ian@fermented-beans:~/Documents/oss/micro/micro-manager$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-linux64) (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-linux64) (build 25.312-b07, mixed mode)

**Comment by nicost** [comment]
If you compiled with JDK8 as the target, you should not have to recompile.  I have a multiple monitor setup (both monitors same size) where MM runs without issues.  The window handling code is going through quite a few hoops to handle multiple monitors (of different sizes) gracefully and seems to work OK on Mac and Windows.  Without being able to step through that code in a debugger, I am not quite sure what to do.

You could try to change line 216:

`GraphicsConfiguration best = null; `

to 

`GraphicsConfiguration best = getConfigs().get(0);`

and see what happens.  Not pretty.  I assume that the real problem is that - for whatever reason - none of the GraphicsEnvironments in your configuration intersect with 0,0.  For the fun of it you could try changing that to 1,1 (that would be a classic;).

**Comment by RileyMShea** [comment]
> none of the GraphicsEnvironments in your configuration intersect with 0,0

That was the issue on Ubuntu Linux for me.

In my case, I have one monitor that is smaller than the other two(1680 vs 1920), and that had a position offset of 30 in nvidia settings:
![image](https://user-images.githubusercontent.com/10238802/177418455-32da9bd7-6113-4dca-a37f-c051309df2b4.png)


### Workaround

I changed the position to have a vertical offset of zero and that allowed `getGraphicsConfiguration` to find the hardcoded x:0,y:0 configuration, which fixed the crash at launch.

---
I don't know what code-based solution works best to handle this(if any), but I guess it should be noted that there's a reasonable probability that any linux machine with multiple monitors(or perhaps even just one) may have a non-zero position offset on what would otherwise be the x:0,y:0 monitor, and that will crash micro-manager at launch.

**Comment by marktsuchida** [comment]
Thank you, @RileyMShea, for the helpful description.

I think a proper fix could be done by getting all the `GraphicsConfiguration`s and finding the one whose top-left is closest to (0, 0).

**Comment by LeanderJDev** [comment]
I ran into the same issue today. I am using Ubuntu 24.04 and have 3 monitors connected 24"|32"|24" and the right one being in rotated 90°.
Is this issue still being worked on? I would love to use µManager, but can't run it this way

**Comment by marktsuchida** [comment]
I'll try to take a look soon; already have a dual-monitor PC with 24.04 available. Just to save time reproducing, which OpenJDK version are you using (for build and at run time)?

**Comment by LeanderJDev** [comment]
Thank you, I am actually not sure which java version I am using, I have JDK 8, 11 and 21 installed, `java --version` returns 21. I used the Ubuntu Quickstart Commands from [docs/how-to-build](https://github.com/micro-manager/micro-manager/blob/main/doc/how-to-build.md).

I did actually look into it myself yesterday too, but I was not able to get it to build `mmstudio`. When running just `make` it always just built `mmCoreAndDevices` and didn't look at the `mmstudio` files (like `GUIUtils`). So then I tried using IntelliJ IDEA, but there it had problems finding `mmcorej`. It just kind of seems like the [IntelliJ Setup Instructions](https://micro-manager.org/Using_IntelliJ) are mostly written for Mac / Windows (due to the nightly build). I would like to figure this out, but maybe this would be a new issue.

Anyway the main problem is, that this code block has a `null` return path:
https://github.com/micro-manager/micro-manager/blob/47298d8df3a3c8013a900e5d7274a8c7e46948a7/mmstudio/src/main/java/org/micromanager/internal/utils/GUIUtils.java#L196-L205

As stated before this happens, when the monitor setup is configured in a way, where the top-left corner of the bounding box around all monitor bounds doesn't land inside a monitor, because the left-most monitor is not the highest one.

This is my default setup, which doesn't work:
<img width="234" height="99" alt="Image" src="https://github.com/user-attachments/assets/41cdf7a9-bd90-4e69-b18c-2b0496b7b125" />

but this setup actually works:
<img width="234" height="99" alt="Image" src="https://github.com/user-attachments/assets/6a55513b-22f4-4421-906e-d9de7347b125" />

**Comment by LeanderJDev** [comment]
Because I was able to run it with the adjusted monitor setup I was also able to crash it, and it seems it uses OpenJDK 21
