### ISSUE TITLE
Acquire broken on linux

### ISSUE THREAD

**Issue by ianhi** [micro-manager/micro-manager#1429]
Fails with this error:

![image](https://user-images.githubusercontent.com/10111092/159042103-fb552cf8-a7a5-4a2a-a795-31de92e7a15e.png)

```
2022-03-18T12:20:33.640751 tid139819709904448 [IFO,App] 
                                              [       ] java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @38a8f1a9 in Thread[AWT-EventQueue-0,6,main]
                                              [       ]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
                                              [       ]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
                                              [       ]   at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
                                              [       ]   at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:116)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
                                              [       ]   at com.google.gson.Gson.getAdapter(Gson.java:356)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
                                              [       ]   at com.google.gson.Gson.getAdapter(Gson.java:356)
                                              [       ]   at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
                                              [       ]   at com.google.gson.Gson.getAdapter(Gson.java:356)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
                                              [       ]   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
                                              [       ]   at com.google.gson.Gson.getAdapter(Gson.java:356)
                                              [       ]   at com.google.gson.Gson.toJson(Gson.java:585)
                                              [       ]   at com.google.gson.Gson.toJson(Gson.java:572)
                                              [       ]   at com.google.gson.Gson.toJson(Gson.java:527)
                                              [       ]   at com.google.gson.Gson.toJson(Gson.java:507)
                                              [       ]   at org.micromanager.acquisition.SequenceSettings.toJSONStream(SequenceSettings.java:837)
                                              [       ]   at org.micromanager.internal.dialogs.AcqControlDlg.saveAcqSettingsToProfile(AcqControlDlg.java:1327)
                                              [       ]   at org.micromanager.internal.dialogs.AcqControlDlg.runAcquisition(AcqControlDlg.java:1533)
                                              [       ]   at org.micromanager.internal.dialogs.AcqControlDlg.lambda$createRunButtons$24(AcqControlDlg.java:838)
                                              [       ]   at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
                                              [       ]   at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
                                              [       ]   at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
                                              [       ]   at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
                                              [       ]   at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
                                              [       ]   at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
                                              [       ]   at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
                                              [       ]   at java.desktop/java.awt.Component.processEvent(Component.java:6391)
                                              [       ]   at java.desktop/java.awt.Container.processEvent(Container.java:2266)
                                              [       ]   at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
                                              [       ]   at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
                                              [       ]   at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
                                              [       ]   at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
                                              [       ]   at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
                                              [       ]   at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
                                              [       ]   at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
                                              [       ]   at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
                                              [       ]   at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
                                              [       ]   at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
                                              [       ]   at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
                                              [       ]   at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
                                              [       ]   at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                                              [       ]   at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
                                              [       ]   at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
                                              [       ]   at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
                                              [       ]   at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
                                              [       ]   at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                                              [       ]   at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
                                              [       ]   at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
                                              [       ]   at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
                                              [       ]   at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
                                              [       ]   at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
                                              [       ]   at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
                                              [       ]   at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                                              [       ]   at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by ianhi** [comment]
This one may be my fault - I think my jdk may be version 17

**Comment by ianhi** [comment]
fixed with jdk8
