### ISSUE TITLE
Freezes after choose config screen

### ISSUE THREAD

**Issue by kobayashikirschvink** [micro-manager/micro-manager#1434]
Hi all,

I've been unable to get past the "choose config window" when I launch the program.
I couldn't load the MMconfig_demo.cfg so it doesn't seem to be the microscope's problem.
I end up with just the ImageJ window and nothing else. I attached the CoreLog file and screenshot below.

@ianhi was able to load the same config files when he did it from pymmcore-plus so this seems to be an issue on the java side rather than the C++ core.

Thanks!

![image](https://user-images.githubusercontent.com/52678464/162825306-8d52cdb9-e369-4d13-ac3e-a1392defd180.png)

<details><summary>Core log CLICK ME</summary>
<p>

```
2022-04-11T15:55:56.097545 tid4156 [IFO,LogManager] Enabled primary log file C:\Program Files\Micro-Manager-2.0\CoreLogs\CoreLog20220411T155556_pid12336.txt
2022-04-11T15:55:56.097545 tid4156 [IFO,App] User: Raman
2022-04-11T15:55:56.097545 tid4156 [IFO,App] Host: DESKTOP-LD09UV5
2022-04-11T15:55:56.097545 tid4156 [IFO,App] MM Studio version: 2.0.1 20220401
2022-04-11T15:55:56.097545 tid4156 [IFO,App] MMCore version 10.2.0
2022-04-11T15:55:56.097545 tid4156 [IFO,App] Device API version 70, Module API version 10
2022-04-11T15:55:56.097545 tid4156 [IFO,App] Operating System: Windows 10 (amd64) 10.0
2022-04-11T15:55:56.097545 tid4156 [IFO,App] JVM: Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_152, 64-bit
2022-04-11T15:55:56.403726 tid10832 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.intensity.IntensityInspectorPanelPlugin@19371403
2022-04-11T15:55:56.404724 tid10832 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.metadata.SummaryMetadataInspectorPanelPlugin@7e830a66
2022-04-11T15:55:56.404724 tid10832 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.metadata.PlaneMetadataInspectorPanelPlugin@772a5dc2
2022-04-11T15:55:56.404724 tid10832 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.comments.CommentsInspectorPanelPlugin@71921d13
2022-04-11T15:55:56.405721 tid10832 [IFO,App] Found plugin org.micromanager.display.overlay.internal.overlays.PatternOverlayPlugin@2162efcf
2022-04-11T15:55:56.405721 tid10832 [IFO,App] Found plugin org.micromanager.display.inspector.internal.panels.overlays.OverlaysInspectorPanelPlugin@40790475
2022-04-11T15:55:56.405721 tid10832 [IFO,App] Found plugin org.micromanager.display.overlay.internal.overlays.ScaleBarPlugin@e846fe0
2022-04-11T15:55:56.405721 tid10832 [IFO,App] Found plugin org.micromanager.display.overlay.internal.overlays.TimestampPlugin@112ead16
2022-04-11T15:55:56.405721 tid10832 [IFO,App] Found plugin org.micromanager.acquisition.internal.DefaultMDAPlugin@2784346b
2022-04-11T15:55:56.405721 tid10832 [IFO,App] Found plugin org.micromanager.display.internal.gearmenu.CopyToImageJItem@2fd6c642
2022-04-11T15:55:56.406718 tid10832 [IFO,App] Found plugin org.micromanager.display.internal.gearmenu.ExportImagesItem@2005737
2022-04-11T15:55:56.406718 tid10832 [IFO,App] Found plugin org.micromanager.display.internal.gearmenu.LineProfileItem@66a20c7c
2022-04-11T15:55:56.407716 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.AutofocusButtons@75d46216
2022-04-11T15:55:56.407716 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.CloseAllButton@7f0916aa
2022-04-11T15:55:56.407716 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.ExposureTime@6676de34
2022-04-11T15:55:56.408712 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.LiveButton@3bcae8b5
2022-04-11T15:55:56.409711 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.MDAButtons@7d32805b
2022-04-11T15:55:56.410708 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.PresetButton@1c05debe
2022-04-11T15:55:56.410708 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.RefreshButton@755cb53d
2022-04-11T15:55:56.410708 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.SavedMDAButton@28d798ab
2022-04-11T15:55:56.411705 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.ScriptButton@1378b06c
2022-04-11T15:55:56.411705 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.ShutterControl@7fe7068
2022-04-11T15:55:56.411705 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.SnapButton@6b3c16fd
2022-04-11T15:55:56.411705 tid10832 [IFO,App] Found plugin org.micromanager.quickaccess.internal.controls.TextLabel@1fb546c2
2022-04-11T15:55:56.411705 tid10832 [IFO,App] Plugin loading took 703ms
2022-04-11T15:55:56.412702 tid4156 [IFO,App] Finished waiting for plugins to load
2022-04-11T15:56:00.836571 tid4156 [IFO,App] 
                                   [       ] java.lang.NullPointerException in Thread[AWT-EventQueue-0,6,main]
                                   [       ]   at org.micromanager.internal.dialogs.AcqControlDlg.<init>(AcqControlDlg.java:296)
                                   [       ]   at org.micromanager.internal.MMUIManager.getAcquisitionWindow(MMUIManager.java:142)
                                   [       ]   at org.micromanager.internal.MMStudio.<init>(MMStudio.java:404)
                                   [       ]   at MMStudioPlugin$1.run(MMStudioPlugin.java:83)
                                   [       ]   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
                                   [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
                                   [       ]   at java.awt.EventQueue.access$500(EventQueue.java:97)
                                   [       ]   at java.awt.EventQueue$3.run(EventQueue.java:709)
                                   [       ]   at java.awt.EventQueue$3.run(EventQueue.java:703)
                                   [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                   [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                                   [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
                                   [       ]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                                   [       ]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                                   [       ]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                                   [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                                   [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                                   [       ]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

</p>
</details>

**Comment by nicost** [comment]
Which OS is this?  Which MM version?  Can you check the Corelogs directory and post the relevant section of the latest Corelog (if any)?

**Comment by kobayashikirschvink** [comment]
I am using Windows 10, and MM version is 2.0.1 20220401. I have also attached the full Corelog in my first post below the screenshot (it says "Core log click me").

Thanks!

```
2022-04-11T17:18:09.043385 tid8436 [IFO,LogManager] Enabled primary log file C:\Program Files\Micro-Manager-2.0\CoreLogs\CoreLog20220411T171809_pid9172.txt
2022-04-11T17:18:09.043385 tid8436 [IFO,App] User: Raman
2022-04-11T17:18:09.043385 tid8436 [IFO,App] Host: DESKTOP-LD09UV5
2022-04-11T17:18:09.043385 tid8436 [IFO,App] MM Studio version: 2.0.1 20220401
2022-04-11T17:18:09.043385 tid8436 [IFO,App] MMCore version 10.2.0
2022-04-11T17:18:09.043385 tid8436 [IFO,App] Device API version 70, Module API version 10
2022-04-11T17:18:09.043385 tid8436 [IFO,App] Operating System: Windows 10 (amd64) 10.0
2022-04-11T17:18:09.043385 tid8436 [IFO,App] JVM: Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_152, 64-bit
```

**Comment by ianhi** [comment]
Hi Nico,

The core log is there in the expandable details block at the bottom. The short of it is windows 10 and we saw this even after updating to the latest nightly build. 

One maybe important piece of information is that there was a power outage on Saturday, which may explain why this worked last week but not this week

**Comment by nicost** [comment]
Ah!  i believe that the user Profile is corrupt.  You can test this by creating a new profile in the "Startup Configuration" window.  If that works, delete the faulty profile.

**Comment by ianhi** [comment]
@nicost that seems to have done the trick thank you! 

Would it be possible to catch error messages like this (I imagine in some restore window state method?) and display an error message suggesting somethign like that?

**Comment by nicost** [comment]
I looked at that, and it is very complicated.  Deleting for now, but feel free to open a new issue with something along the lines of "Need better error reporting when profile is corrupt."
