### ISSUE TITLE
mm2: Clicking the Windowed button in Full Screen mode results in an exception

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#150]
Tested with a real camera (Hamamatsu Flash 4.0) on Windows 7, running under Netbeans.  Snap an image, click on the Full screen button, then on Windows button results in the exception copied below.  The same sequence of events in the nightly build also locks up the UI, so likely unrelated to Netbeans.

2016-01-25T17:53:55.163271 tid15032 [IFO,App] java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is org.micromanager.quickaccess.internal.controls.LiveButton$3@4142e23f registered?
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at com.google.common.eventbus.EventBus.unregister(EventBus.java:230)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at org.micromanager.events.internal.DefaultEventManager.unregisterForEvents(DefaultEventManager.java:28)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at org.micromanager.quickaccess.internal.controls.LiveButton$3.hierarchyChanged(LiveButton.java:134)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.processHierarchyEvent(Component.java:6464)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.processEvent(Component.java:6083)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.processEvent(Container.java:2039)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.dispatchEventImpl(Component.java:4660)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2097)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4488)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.removeNotify(Component.java:6838)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.removeNotify(Container.java:2614)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.JComponent.removeNotify(JComponent.java:4709)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.AbstractButton.removeNotify(AbstractButton.java:1011)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.JButton.removeNotify(JButton.java:217)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.removeNotify(Container.java:2607)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.JComponent.removeNotify(JComponent.java:4709)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.removeNotify(Container.java:2607)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.JComponent.removeNotify(JComponent.java:4709)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.removeNotify(Container.java:2607)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.JComponent.removeNotify(JComponent.java:4709)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.remove(Container.java:1138)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.remove(Container.java:1196)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.addImpl(Container.java:1044)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.add(Container.java:957)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.JFrame.addImpl(JFrame.java:540)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.add(Container.java:363)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at org.micromanager.display.internal.DefaultDisplayWindow.toggleFullScreen(DefaultDisplayWindow.java:941)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at org.micromanager.display.internal.ButtonPanel$1.actionPerformed(ButtonPanel.java:82)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:272)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.processMouseEvent(Component.java:6297)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.processEvent(Component.java:6062)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.processEvent(Container.java:2039)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.dispatchEventImpl(Component.java:4660)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2097)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4488)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4236)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2083)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Window.dispatchEventImpl(Window.java:2489)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4488)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:668)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventQueue.access$400(EventQueue.java:81)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventQueue$2.run(EventQueue.java:627)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventQueue$2.run(EventQueue.java:625)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:641)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:639)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:638)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
2016-01-25T17:53:55.163271 tid15032 [IFO,App]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by ChrisWeisiger** [comment]
Thanks for the report. This turned out to be due to the Snap/Live buttons in the Live window being redundantly unsubscribed from events, which causes an IllegalArgumentException. This is now fixed.
