### ISSUE TITLE
Micro-Manager application hangs on exit

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1518]
Corelog shows this is coming from the EMU plugin.  However, I also think that such errors should never prevent the application from exiting, and should be caught somewhere higher up:

2022-09-15T10:27:56.568547 tid12432 [IFO,App] Thread 29 (AWT-EventQueue-0) terminated with uncaught exception
2022-09-15T10:27:56.568547 tid12432 [IFO,App] java.lang.NoClassDefFoundError: com/jacob/com/STA
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.defineClass1(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at ModularPlugin.OnShutdown(ModularPlugin.java:350)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.reflect.Method.invoke(Method.java:498)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at org.micromanager.events.internal.DefaultEventManager.post(DefaultEventManager.java:47)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at org.micromanager.internal.MMStudio.closeSequence(MMStudio.java:752)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at org.micromanager.internal.MainFrame$1.windowClosing(MainFrame.java:201)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Window.processWindowEvent(Window.java:2054)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Window.processEvent(Window.java:2013)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Component.dispatchEventImpl(Component.java:4889)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2295)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Window.dispatchEventImpl(Window.java:2746)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4711)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue.access$500(EventQueue.java:97)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:709)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:703)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:731)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:729)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2022-09-15T10:27:56.568547 tid12432 [IFO,App] Caused by exception:
2022-09-15T10:27:56.568547 tid12432 [IFO,App] java.lang.ClassNotFoundException: com.jacob.com.STA
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.defineClass1(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at ModularPlugin.OnShutdown(ModularPlugin.java:350)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.lang.reflect.Method.invoke(Method.java:498)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at org.micromanager.events.internal.DefaultEventManager.post(DefaultEventManager.java:47)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at org.micromanager.internal.MMStudio.closeSequence(MMStudio.java:752)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at org.micromanager.internal.MainFrame$1.windowClosing(MainFrame.java:201)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Window.processWindowEvent(Window.java:2054)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Window.processEvent(Window.java:2013)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Component.dispatchEventImpl(Component.java:4889)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Container.dispatchEventImpl(Container.java:2295)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Window.dispatchEventImpl(Window.java:2746)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.Component.dispatchEvent(Component.java:4711)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue.access$500(EventQueue.java:97)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:709)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue$3.run(EventQueue.java:703)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:731)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue$4.run(EventQueue.java:729)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.AccessController.doPrivileged(Native Method)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
2022-09-15T10:27:56.568547 tid12432 [IFO,App]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nicost** [comment]
This was not the EMU plugin, but a proprietary one.  Catching the exception did not help.  Cosing until it becomes a real issue.
