### ISSUE TITLE
Micro-Magellan broken

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1677]
MM distribution 20230331, start an Explore Acquisition in the Micro-Magellen plugin.  No image shows up, Corelog shows:

```
2023-04-10T10:19:07.376001 tid10496 [IFO,App] Thread 283 (Thread-226) terminated with uncaught exception
2023-04-10T10:19:07.376034 tid10496 [IFO,App] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2023-04-10T10:19:07.376118 tid10496 [IFO,App]   at java.util.ArrayList.rangeCheck(ArrayList.java:657)
2023-04-10T10:19:07.376120 tid10496 [IFO,App]   at java.util.ArrayList.get(ArrayList.java:433)
2023-04-10T10:19:07.376122 tid10496 [IFO,App]   at org.micromanager.acqj.util.AcqEventModules$4.next(AcqEventModules.java:132)
2023-04-10T10:19:07.376123 tid10496 [IFO,App]   at org.micromanager.acqj.util.AcqEventModules$4.next(AcqEventModules.java:121)
2023-04-10T10:19:07.376126 tid10496 [IFO,App]   at org.micromanager.acqj.util.AcquisitionEventIterator.next(AcquisitionEventIterator.java:44)
2023-04-10T10:19:07.376127 tid10496 [IFO,App]   at org.micromanager.acqj.util.AcquisitionEventIterator.next(AcquisitionEventIterator.java:16)
2023-04-10T10:19:07.376129 tid10496 [IFO,App]   at org.micromanager.explore.ExploreAcquisition.submitEvents(ExploreAcquisition.java:313)
2023-04-10T10:19:07.376130 tid10496 [IFO,App]   at org.micromanager.explore.ExploreAcquisition.lambda$acquireTiles$3(ExploreAcquisition.java:271)
2023-04-10T10:19:07.376132 tid10496 [IFO,App]   at java.lang.Thread.run(Thread.java:748)
2023-04-10T10:19:10.095117 tid5352 [IFO,App] Thread 284 (Thread-227) terminated with uncaught exception
2023-04-10T10:19:10.095133 tid5352 [IFO,App] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2023-04-10T10:19:10.095169 tid5352 [IFO,App]   at java.util.ArrayList.rangeCheck(ArrayList.java:657)
2023-04-10T10:19:10.095171 tid5352 [IFO,App]   at java.util.ArrayList.get(ArrayList.java:433)
2023-04-10T10:19:10.095173 tid5352 [IFO,App]   at org.micromanager.acqj.util.AcqEventModules$4.next(AcqEventModules.java:132)
2023-04-10T10:19:10.095174 tid5352 [IFO,App]   at org.micromanager.acqj.util.AcqEventModules$4.next(AcqEventModules.java:121)
2023-04-10T10:19:10.095177 tid5352 [IFO,App]   at org.micromanager.acqj.util.AcquisitionEventIterator.next(AcquisitionEventIterator.java:44)
2023-04-10T10:19:10.095178 tid5352 [IFO,App]   at org.micromanager.acqj.util.AcquisitionEventIterator.next(AcquisitionEventIterator.java:16)
2023-04-10T10:19:10.095180 tid5352 [IFO,App]   at org.micromanager.explore.ExploreAcquisition.submitEvents(ExploreAcquisition.java:313)
2023-04-10T10:19:10.095182 tid5352 [IFO,App]   at org.micromanager.explore.ExploreAcquisition.lambda$acquireTiles$3(ExploreAcquisition.java:271)
2023-04-10T10:19:10.095184 tid5352 [IFO,App]   at java.lang.Thread.run(Thread.java:748)
2023-04-10T10:19:46.179674 tid8872 [IFO,App] Thread 312 (Thread-245) terminated with uncaught exception
2023-04-10T10:19:46.179696 tid8872 [IFO,App] java.lang.NullPointerException
2023-04-10T10:19:46.179730 tid8872 [IFO,App]   at org.micromanager.ndtiffstorage.StorageMD.getPixelOverlapX(StorageMD.java:61)
2023-04-10T10:19:46.179733 tid8872 [IFO,App]   at org.micromanager.ndtiffstorage.NDTiffStorage.<init>(NDTiffStorage.java:150)
2023-04-10T10:19:46.179735 tid8872 [IFO,App]   at org.micromanager.magellan.internal.magellanacq.MagellanAcqUIAndStorage.<init>(MagellanAcqUIAndStorage.java:128)
2023-04-10T10:19:46.179737 tid8872 [IFO,App]   at org.micromanager.magellan.internal.magellanacq.LoadedAcquisitionData.<init>(LoadedAcquisitionData.java:33)
2023-04-10T10:19:46.179739 tid8872 [IFO,App]   at org.micromanager.magellan.internal.gui.GUI.lambda$openDatasetButtonActionPerformed$43(GUI.java:2034)
2023-04-10T10:19:46.179742 tid8872 [IFO,App]   at java.lang.Thread.run(Thread.java:748)
2023-04-10T10:20:19.523021 tid16196 [IFO,dev:CSUW1-SoraMagnifier] Get FRAP answer is: 2:A
```

@henrypinkard any ideas?  Is there some automated testing that can catch problems like these?

**Comment by henrypinkard** [comment]
Not seeing this with latest continuous integration build and demo configuration. Are you accidentally using an older version? or is this something hardware related?

Could probably expand out this automated pycromanager tests to cover more explore-like syntax, though I don't know if its possible to test the UI. But now that explore is split into a separate module, it can in theory be more stable

**Comment by nicost** [comment]
Using MM distribution 20230331.  Do not know if this is hardware related, would have expected an error message to that effect.  Everything else works fine with this hardware...

**Comment by henrypinkard** [comment]
works for me on[ latest CI build](https://download.micro-manager.org/ci/2.0/Windows/MMSetup_64bit_7b250a5_20230411.exe)

**Comment by nicost** [comment]
Great that it works for you, it does work for me on my laptop with the demo configuration, but with real hardware, nada..  Currently even no output in the Corelog.  It popped up one error message at one point, but it was an empty error message (i.e. no text displayed).  May this be related to the recent addition of extra z stages?  The limits menu looks very strange, with limits for the piezo set to 100-100 (it has a range of 0-200). the PFS Offset set to 100-9238.0 (current setting is 9238.0), and Z Drive of 100-6832 (range is 0-100000, current value is 6832).  Any ideas how to proceed?

**Comment by henrypinkard** [comment]
I've just made a bunch of fixes and improvements to acquisition engine, so there is an outside chance its been fixed already.

If not, probably need to set up a debug session with the acquisition engine and step through. [This ](https://github.com/micro-manager/AcqEngJ/blob/9a113bfc032160c90739461615aa615e41d71026/src/main/java/org/micromanager/acqj/internal/Engine.java#L119 )would be a good place to start.

> The limits menu looks very strange, with limits for the piezo set to 100-100 (it has a range of 0-200). the PFS Offset set to 100-9238.0 (current setting is 9238.0), and Z Drive of 100-6832 (range is 0-100000, current value is 6832). Any ideas how to proceed?

These are auto expanding scrollbars. If you click in the empty space on either side (or the arrows) their min and max extent will change. This is because there is no way to get the limits of a StageDevice in the core. (Though strangely, I now notice this in the Stage API. Was this just never exposed?)

sounds like there is a bug in there where its getting lower limits for stages 2 and three from the current position of stage 1

**Comment by henrypinkard** [comment]
You are the first to test this on actual hardware with multiple z stages as far as i know, so there may be bumps along the way

**Comment by nicost** [comment]
I'll wait for tonight's build.  Setting up a development environment on the microscope system will be some work.  IT is most perplexing that no error messages are logged.  There must be exceptions somewhere.  Does the acquisition engine log those somewhere else than in the Corelog?

**Comment by henrypinkard** [comment]
> The limits menu looks very strange, with limits for the piezo set to 100-100 (it has a range of 0-200). the PFS Offset set to 100-9238.0 (current setting is 9238.0), and Z Drive of 100-6832 (range is 0-100000, current value is 6832). Any ideas how to proceed?

fixed by https://github.com/micro-manager/pycro-manager/pull/583

**Comment by henrypinkard** [comment]
> IT is most perplexing that no error messages are logged. There must be exceptions somewhere. Does the acquisition engine log those somewhere else than in the Corelog?

there may be some stacktraces printed. Also would help to turn on `acq.setDebugMode(true)`

**Comment by nicost** [comment]
Was fixed since checking last.
