### ISSUE TITLE
NDTiff Reader broken (at least for NDTIff 3.2 datasets)

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1806]
The latest NDTIff Storage update broke the NDTiff Reader in Micro-Manager.  When opening a datasets where the channels have names rather than numbers, the following null pointer exception appears:
2023-10-02T14:41:37.811994 tid33588 [IFO,App] Thread 44 (Thread-7) terminated with uncaught exception
2023-10-02T14:41:37.812049 tid33588 [IFO,App] java.lang.NullPointerException
2023-10-02T14:41:37.812342 tid33588 [IFO,App]   at org.micromanager.data.internal.ndtiff.NDTiffAdapter.hashMapToCoords(NDTiffAdapter.java:107)
2023-10-02T14:41:37.812351 tid33588 [IFO,App]   at org.micromanager.data.internal.ndtiff.NDTiffAdapter.getAnyImage(NDTiffAdapter.java:219)
2023-10-02T14:41:37.812358 tid33588 [IFO,App]   at org.micromanager.data.internal.DefaultDatastore.getAnyImage(DefaultDatastore.java:186)
2023-10-02T14:41:37.812364 tid33588 [IFO,App]   at org.micromanager.data.internal.DefaultDataManager.loadData(DefaultDataManager.java:242)
2023-10-02T14:41:37.812370 tid33588 [IFO,App]   at org.micromanager.data.internal.DefaultDataManager.promptForDataToLoad(DefaultDataManager.java:203)
2023-10-02T14:41:37.812376 tid33588 [IFO,App]   at org.micromanager.internal.menus.FileMenu.lambda$promptToOpenFile$4(FileMenu.java:104)

The code expects a number, but gets a String apparently, (this change was introduced in NDTiff v3.2).  It is unclear to me how to map that String to a number, I can not find a function in the the NDTiff API that gives me a mapping of names to numbers.  I can make one up myself, but then certainly will break something.

**Comment by henrypinkard** [comment]
How did you generate this dataset? Can you send me or post an example? My understanding was that MMStudio (implicitly) doesn't use string-valued axes, so I'm curious as to how you ran into this. Should be a straightforward fix though.


> The latest NDTIff Storage update broke the NDTiff Reader in Micro-Manager.

Which change are you referring to? [This one](https://github.com/micro-manager/NDTiffStorage/commit/e8138580b9eebaa22800dcfdb4ec66596ed20023)?

It would be very helpful to fixing these things if you could provide more specificity about conditions for reproducing, since there are many different moving pieces here.
