### ISSUE TITLE
Exiting MM with Device Property Browser open leads to an Exception

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1811]
2023-10-10T12:28:14.764657 tid25920 [IFO,Core] Core session ended
Thread 22 (AWT-EventQueue-0) terminated with uncaught exception
java.lang.NullPointerException
  at org.micromanager.internal.utils.ShowFlags.save(ShowFlags.java:70)
  at org.micromanager.internal.PropertyEditor$1.windowClosing(PropertyEditor.java:126)
  at java.awt.Window.processWindowEvent(Window.java:2054)
  at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
  at java.awt.Window.processEvent(Window.java:2013)
  at java.awt.Component.dispatchEventImpl(Component.java:4889)
  at java.awt.Container.dispatchEventImpl(Container.java:2295)
  at java.awt.Window.dispatchEventImpl(Window.java:2746)
  at java.awt.Component.dispatchEvent(Component.java:4711)
  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
  at java.awt.EventQueue.access$500(EventQueue.java:97)
  at java.awt.EventQueue$3.run(EventQueue.java:709)
  at java.awt.EventQueue$3.run(EventQueue.java:703)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
  at java.awt.EventQueue$4.run(EventQueue.java:731)
  at java.awt.EventQueue$4.run(EventQueue.java:729)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
  at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by nicost** [comment]
Likely fixed in #1817
