### ISSUE TITLE
mm2: Duplicator plugin doesn't open window on Windows

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#389]
The Duplicator plugin (#373) works perfectly on OS X but fails to show the little settings window when tested on Windows 7.

Appears to be due to Windows path separator being backslash:
```
[UI] GearButton clicked in DefaultDisplayWindow.
Thread 15 (AWT-EventQueue-0) terminated with uncaught exception
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
  at java.util.regex.Pattern.error(Unknown Source)
  at java.util.regex.Pattern.compile(Unknown Source)
  at java.util.regex.Pattern.<init>(Unknown Source)
  at java.util.regex.Pattern.compile(Unknown Source)
  at java.lang.String.split(Unknown Source)
  at java.lang.String.split(Unknown Source)
  at org.micromanager.duplicator.DuplicatorPluginFrame.<init>(DuplicatorPluginFrame.java:84)
  at org.micromanager.duplicator.DuplicatorPlugin.onPluginSelected(DuplicatorPlugin.java:53)
  at org.micromanager.display.internal.gearmenu.GearButton$3.actionPerformed(GearButton.java:83)
  at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[truncated]
```

**Comment by nicost** [comment]
Just noted this.  Fixed in pull requesy #395
