### ISSUE TITLE
mm2: global user profile not found at startup

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#61]
I get the following on stderr before the CoreLog starts up (not just the first time; every time).
If GlobalUserProfile.txt is optional and the error is benign, the exception should not be printed.

Seen on Windows when from command line (`./jre/bin/java -Xmx2048m -cp ij.jar ij.ImageJ`).

```
Unable to read file at C:\Program Files\Micro-Manager-2.0.0-alpha1\GlobalUserProfile.txt
java.io.FileNotFoundException: C:\Program Files\Micro-Manager-2.0.0-alpha1\GlobalUserProfile.txt (The system cannot find the file specified) in Thread[AWT-EventQueue-0,6,main]
  at java.io.FileInputStream.open(Native Method)
  at java.io.FileInputStream.<init>(Unknown Source)
  at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
  at com.google.common.io.Files$FileByteSource.openStream(Files.java:116)
  at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
  at com.google.common.io.CharSource.read(CharSource.java:162)
  at com.google.common.io.Files.toString(Files.java:367)
  at org.micromanager.internal.utils.DefaultUserProfile.loadFileToString(DefaultUserProfile.java:170)
  at org.micromanager.internal.utils.DefaultUserProfile.loadPropertyMap(DefaultUserProfile.java:146)
  at org.micromanager.internal.utils.DefaultUserProfile.<init>(DefaultUserProfile.java:57)
  at org.micromanager.internal.utils.DefaultUserProfile.<clinit>(DefaultUserProfile.java:41)
  at org.micromanager.internal.dialogs.OptionsDlg.getIsDebugLogEnabled(OptionsDlg.java:365)
  at org.micromanager.internal.MMStudio.<init>(MMStudio.java:251)
  at MMStudioPlugin$1.run(MMStudioPlugin.java:82)
  at java.awt.event.InvocationEvent.dispatch(Unknown Source)
  at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
  at java.awt.EventQueue.access$000(Unknown Source)
  at java.awt.EventQueue$1.run(Unknown Source)
  at java.awt.EventQueue$1.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
  at java.awt.EventQueue.dispatchEvent(Unknown Source)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
  at java.awt.EventDispatchThread.run(Unknown Source)


Asked to load file at path C:\Program Files\Micro-Manager-2.0.0-alpha1\GlobalUserProfile.txt which doesn't exist; instead providing a default empty PropertyMap.
```

**Comment by ChrisWeisiger** [comment]
Fixed in 8f25ff564f2cb3789ba5ac99ed41f88aa7f53045
