### ISSUE TITLE
Boost Thread version issue during Linux build

### ISSUE THREAD

**Issue by hadim** [micro-manager/micro-manager#612]
I am trying to build MM on Ubuntu and got an undefined symbol on boost thread library. I am using Ubuntu 17.10 that ships with Boost 1.62 by default. If you think the issue is related to Boost version incompatibility, would that be possible to make it worked with Boost 1.62?

Here is the script I am using to build MM: https://github.com/hadim/mm_scripts/blob/master/build-mm.sh

And here is the error I got:

```
$ ./mmimagej 
Load MMCoreJ_wrap: Start loading...
Load MMCoreJ_wrap: Will search in hard-coded paths:
Load MMCoreJ_wrap:   /home/hadim/local/mm/Fiji.app/plugins/Micro-Manager
Load MMCoreJ_wrap:   /home/hadim/local/mm/Fiji.app/plugins
Load MMCoreJ_wrap:   /home/hadim/local/mm/Fiji.app/plugins/mm/linux64
Load MMCoreJ_wrap:   /home/hadim/local/mm/Fiji.app
Load MMCoreJ_wrap:   /home/hadim/local/mm/Fiji.app/mm/linux64
Load MMCoreJ_wrap:   /usr/local/lib/micro-manager
Load MMCoreJ_wrap: Skipping nonexistent candidate: /home/hadim/local/mm/Fiji.app/plugins/Micro-Manager/libMMCoreJ_wrap.so
Load MMCoreJ_wrap: Skipping nonexistent candidate: /home/hadim/local/mm/Fiji.app/plugins/libMMCoreJ_wrap.so
Load MMCoreJ_wrap: Skipping nonexistent candidate: /home/hadim/local/mm/Fiji.app/plugins/mm/linux64/libMMCoreJ_wrap.so
Load MMCoreJ_wrap: Try loading: /home/hadim/local/mm/Fiji.app/libMMCoreJ_wrap.so
Failed to load the MMCoreJ_wrap native library
java.lang.UnsatisfiedLinkError: /home/hadim/local/mm/Fiji.app/libMMCoreJ_wrap.so: /home/hadim/local/mm/Fiji.app/libMMCoreJ_wrap.so: undefined symbol: _ZTIN5boost6detail16thread_data_baseE in Thread[AWT-EventQueue-1,6,main]
  at java.lang.ClassLoader$NativeLibrary.load(Native Method)
  at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
  at java.lang.Runtime.load0(Runtime.java:809)
  at java.lang.System.load(System.java:1086)
...
```

Ping @marktsuchida 

PS: also would be ok if I submit a PR with a Travis script so we can track this kind of issue in the future? And also possibly upload the generated MicroManager bundle somewhere else so people can easily download and run MM without building it?

**Comment by hadim** [comment]
Also, see https://github.com/micro-manager/micro-manager/pull/613/files#diff-96ccae42f0b749f5b34f09dc786b018bL31 that fix compilation under Linux.

**Comment by hadim** [comment]
It's finally working with a modification of the above script where I download an old boost version. Hopefully boost will get updated at some point.

https://github.com/hadim/mm_scripts/blob/master/build-mm.sh
