### ISSUE TITLE
Display of more than one RGB image is broken

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#729]
Steps to reproduce:
- Load Demo configuration
- Set DemoCamera to 32bitRGB
- Run an MDA with 2 time points, nothing else selected.
- Observe that the display behaves strange, and find the followin stack trace:

2020-03-23T14:14:43.989989 tid17432 [IFO,App] java.lang.IllegalArgumentException: n out of range: 2
2020-03-23T14:14:43.989989 tid17432 [IFO,App]   at ij.ImagePlus.convertIndexToPosition(ImagePlus.java:1540)
2020-03-23T14:14:43.989989 tid17432 [IFO,App]   at org.micromanager.display.internal.displaywindow.imagej.ImageJBridge.getMMCoordsForIJFlatIndex(ImageJBridge.java:491)
2020-03-23T14:14:43.989989 tid17432 [IFO,App]   at org.micromanager.display.internal.displaywindow.imagej.MMVirtualStack.getProcessor(MMVirtualStack.java:129)
2020-03-23T14:14:43.989989 tid17432 [IFO,App]   at org.micromanager.display.internal.displaywindow.imagej.ImageJBridge.mm2ijSetDisplayPosition(ImageJBridge.java:365)
2020-03-23T14:14:43.989989 tid17432 [IFO,App]   at org.micromanager.display.internal.displaywindow.DisplayUIController.displayImages(DisplayUIController.java:785)
2020-03-23T14:14:43.989989 tid17432 [IFO,App]   at org.micromanager.display.internal.displaywindow.DisplayController$1.run(DisplayController.java:410)
2020-03-23T14:14:43.989989 tid17432 [IFO,App]   at org.micromanager.internal.utils.CoalescentEDTRunnablePool$2.run(CoalescentEDTRunnablePool.java:132)
2020-03-23T14:14:43.989989 tid17432 [IFO,App]   at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)

**Comment by nicost** [comment]
Fixed in PR #732
