### ISSUE TITLE
ImageFlipper does not work with RGB32 images

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#820]
2020-06-01T21:47:54.971149 tid10196 [IFO,App] Processor failed to process image
                                    [       ] java.lang.UnsupportedOperationException: Unsupported pixel data type in Thread[AWT-EventQueue-0,6,main]
                                    [       ]   at org.micromanager.data.internal.DefaultImage.<init>(DefaultImage.java:207)
                                    [       ]   at org.micromanager.data.internal.DefaultDataManager.createImage(DefaultDataManager.java:274)
                                    [       ]   at org.micromanager.data.internal.DefaultImageJConverter.createImage(DefaultImageJConverter.java:155)
                                    [       ]   at org.micromanager.imageflipper.FlipperProcessor.transformImage(FlipperProcessor.java:121)
                                    [       ]   at org.micromanager.imageflipper.FlipperProcessor.processImage(FlipperProcessor.java:78)

**Comment by nicost** [comment]
Fixed in #821
