### ISSUE TITLE
NullPointerException in DefaultDatastore.freeze()

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/micro-manager#846]
I am currently seeing this in a custom plugin that I am working on though I believe I have also occasionally seen this error when the MDA was used.

In my plugin I am generating `Image` objects which I am then adding to a `Datastore` for the purpose of saving to TIFF. I am also using `SwingUtilities.invokeLater` to display the image in a `DisplayWindow` which is backed by a separate RAM `Datastore`.

This error seems to occur completely at random which makes me think that it has to do with some code that isn't thread safe.

```
2020-06-18T17:44:24.998322 tid5656 [IFO,App] java.lang.NullPointerException
2020-06-18T17:44:24.998322 tid5656 [IFO,App]   at org.micromanager.data.internal.multipagetiff.StorageMultipageTiff.isViewingOurStore(StorageMultipageTiff.java:747)
2020-06-18T17:44:24.998322 tid5656 [IFO,App]   at org.micromanager.data.internal.multipagetiff.StorageMultipageTiff.getDisplaySettings(StorageMultipageTiff.java:720)
2020-06-18T17:44:24.998322 tid5656 [IFO,App]   at org.micromanager.data.internal.multipagetiff.StorageMultipageTiff.getIJDescriptionString(StorageMultipageTiff.java:671)
2020-06-18T17:44:24.998322 tid5656 [IFO,App]   at org.micromanager.data.internal.multipagetiff.StorageMultipageTiff.finished(StorageMultipageTiff.java:491)
2020-06-18T17:44:24.998322 tid5656 [IFO,App]   at org.micromanager.data.internal.multipagetiff.StorageMultipageTiff.freeze(StorageMultipageTiff.java:333)
2020-06-18T17:44:24.998322 tid5656 [IFO,App]   at org.micromanager.data.internal.DefaultDatastore.freeze(DefaultDatastore.java:336)
2020-06-18T17:44:24.998322 tid5656 [IFO,App]   at edu.bpl.pwsplugin.acquisitionManagers.fileSavers.MMSaver.run(MMSaver.java:69)
```

I added some breakpoints to `StorageMultipageTiff.isViewingOurStore` and found that `dpImg` is the variable that is ending up `null`.

The relation between `DataStore`, `DataViewer`, `DataProvider`, etc. is all a bit confusing to me. Does anyone have an idea of what might be causing this?

**Comment by nicost** [comment]
A DataProvider is an object holding data, i.e. images and metadata.  A Datastore is a subclass of a DataProvider and can save this data (naming is not that great, I guess that Datastore could have been names Datawriter or something like that, but we had a Datastore first, and Mark liked having an object with only a subset of the Datastore functionality, hence DataProvider).
A DataViewer provides a view into the DataProvider (i.e., a DataViewer only needs to know about a DataProvider, not about a Datastore).  

The nullpointer exception you encounter is caused because this neat separation of rules falls a bit flat.  The MultiPageTIffWriter tries to provide information that ImageJ will use to open the file looking more or less right to the user.  To do so, it needs to find out which DataViewer is currently displaying its data.  It does so in a roundabout way, by asking MMStudio for all its DataViewers, and then checking all these Viewers by requesting an image, and checking if it matches images in its store.  Apparently, you have DataViewers open that have no images, dp.getAnyImage() returns null, and the code happily throws a NullPointerException.  

This looks all pretty ugly, but better not rock this boat.  It seems quite safe to me to add a check for null on dpImg, and return false if no image was found.
