### ISSUE TITLE
MDA channel settings not handling null correctly

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#915]
I'm seeing a `NullPointerException` during startup (after loading config) caused by the `channels` field in `SequenceSettings` being set to a list containing one or more `null`s. This happens even if no config is loaded.

```
2020-08-26T12:22:08.974147 tid42592 [IFO,App] Thread 18 (AWT-EventQueue-0) terminated with uncaught exception
2020-08-26T12:22:08.974147 tid42592 [IFO,App] java.lang.NullPointerException
2020-08-26T12:22:08.974147 tid42592 [IFO,App]   at org.micromanager.acquisition.internal.AcquisitionWrapperEngine.getNumChannels(AcquisitionWrapperEngine.java:209)
2020-08-26T12:22:08.974147 tid42592 [IFO,App]   at org.micromanager.acquisition.internal.AcquisitionWrapperEngine.getVerboseSummary(AcquisitionWrapperEngine.java:563)
2020-08-26T12:22:08.974147 tid42592 [IFO,App]   at org.micromanager.internal.dialogs.AcqControlDlg.tableChanged(AcqControlDlg.java:1624)
2020-08-26T12:22:08.974147 tid42592 [IFO,App]   at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
2020-08-26T12:22:08.974147 tid42592 [IFO,App]   at javax.swing.table.AbstractTableModel.fireTableStructureChanged(AbstractTableModel.java:216)
2020-08-26T12:22:08.974147 tid42592 [IFO,App]   at org.micromanager.internal.dialogs.AcqControlDlg.lambda$updateGUIFromSequenceSettings$32(AcqControlDlg.java:1121)
2020-08-26T12:22:08.974147 tid42592 [IFO,App]   at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)
2020-08-26T12:22:08.974147 tid42592 [IFO,App]   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
[...]
```

The direct cause, in my case, seems to be that such a `null`-containing list is getting restored from the user profile, having been saved previously (possibly related to my investigation of #891).

We need to document the legal states of the `channels` field (i.e. whether or not `null`s are allowed when there are unchecked channels in the MDA dialog), and make sure all code follows it.

(One possibility that might be worth checking for is that some code could set `channels` to a valid list, but that same list could later be modified by the GUI to contain `null`s -- the `SequenceSettings` builder should probably make copies of any lists being passed in (and out), and perhaps should also perform some validation.)

**Comment by nicost** [comment]
Looking into this now, and will at least provide a temporary fix as this problem affects people with systems they depend on for their work (nixing their profile is not fun).

I am adding a check for null in AcquisitionWrapperEngine.getNumChannels().  That will not change the underlying problem, but at least allow for the UI to show up.

Trying to find out how null can ever be inserted in the list.  There indeed is a place in ChannelTableModel that could have done so.  I am adding a check for null in SequenceSettings.Builder, and ensure that channels are only ever set through the builder.  See upcoming PR.
