### ISSUE TITLE
Magellan: Opening a dataset by selecting a sub-directly leads to null pointer exception

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#959]
@henrypinkard:

Steps to reproduce:
1. Select Plugins > Micro-Magellan
2. Click "Open Dataset"
3. Select any directory that does not contain a Micro-Magellan dataset

Results:
- UI does not provide any feedback
- Logs show a null pointer exception:
2020-09-22T19:57:06.640583 tid22936 [IFO,App] java.lang.NullPointerException
2020-09-22T19:57:06.640583 tid22936 [IFO,App]   at org.micromanager.multiresstorage.ResolutionLevel.openExistingDataSet(ResolutionLevel.java:118)
2020-09-22T19:57:06.640583 tid22936 [IFO,App]   at org.micromanager.multiresstorage.ResolutionLevel.<init>(ResolutionLevel.java:83)
2020-09-22T19:57:06.640583 tid22936 [IFO,App]   at org.micromanager.multiresstorage.MultiResMultipageTiffStorage.<init>(MultiResMultipageTiffStorage.java:89)
2020-09-22T19:57:06.640583 tid22936 [IFO,App]   at org.micromanager.magellan.internal.magellanacq.MagellanDataManager.<init>(MagellanDataManager.java:101)
2020-09-22T19:57:06.640583 tid22936 [IFO,App]   at org.micromanager.magellan.internal.magellanacq.LoadedAcquisitionData.<init>(LoadedAcquisitionData.java:34)
2020-09-22T19:57:06.640583 tid22936 [IFO,App]   at org.micromanager.magellan.internal.gui.GUI$56.run(GUI.java:1949)
2020-09-22T19:57:06.640583 tid22936 [IFO,App]   at java.lang.Thread.run(Thread.java:748)

Desired behavior:
Message in the UI noting that no valid dataset was found.

**Comment by henrypinkard** [comment]
Should be fixed by https://github.com/micro-manager/micro-manager/pull/962
