### ISSUE TITLE
MDA doesn't respond when changing configuration under Channels

### ISSUE THREAD

**Issue by zhangxiaosa** [micro-manager/micro-manager#988]
To reproduce it:
Open MDA.
Tick the checkbox of `Channels`.
Clear all existing Channels and click `new` to create a new one.
Click the the channel name, it is expected to list all available channels, but there is no response.

The bug is clearly located by the error message:
```
2020-10-22T18:44:21.768449 tid16020 [IFO,App] Thread 22 (AWT-EventQueue-0) terminated with uncaught exception
2020-10-22T18:44:21.768449 tid16020 [IFO,App] java.lang.ClassCastException: java.lang.Double cannot be cast to java.awt.Color
2020-10-22T18:44:21.768449 tid16020 [IFO,App]   at org.micromanager.internal.dialogs.ChannelTableModel.setValueAt(ChannelTableModel.java:164)
2020-10-22T18:44:21.769448 tid16020 [IFO,App]   at javax.swing.JTable.setValueAt(JTable.java:2744)
2020-10-22T18:44:21.769448 tid16020 [IFO,App]   at javax.swing.JTable.editingStopped(JTable.java:4729)
2020-10-22T18:44:21.769448 tid16020 [IFO,App]   at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141)
2020-10-22T18:44:21.770447 tid16020 [IFO,App]   at javax.swing.AbstractCellEditor.stopCellEditing(AbstractCellEditor.java:85)
2020-10-22T18:44:21.770447 tid16020 [IFO,App]   at org.micromanager.internal.dialogs.AcqControlDlg$2.windowLostFocus(AcqControlDlg.java:327)
2020-10-22T18:44:21.771446 tid16020 [IFO,App]   at java.awt.Window.processWindowFocusEvent(Window.java:2104)
```

**Comment by zhangxiaosa** [comment]
Plus, all other attributes can't be modified.
